---
ID: "f2cc1f56-307a-4837-a97f-4c2af0e4a557"
Parent: "78d06b51-3fed-4ad3-80f0-aad36c77bbd5"
Template: "78d06b51-3fed-4ad3-80f0-aad36c77bbd5"
Path: /sitecore/templates/Project/Sites/Page/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {78D06B51-3FED-4AD3-80F0-AAD36C77BBD5}
    {C14B6289-8AC2-439C-9E5B-40DE9F820C3F}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1e1e97a6-bf05-462d-bf71-148ad702f4a2"
      Hint: Title
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230525T174618Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\roberto.barbedo@perficient.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\roberto.barbedo@perficient.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1284761a-58ab-4f4e-89d9-4cef2e3118e9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\roberto.barbedo@perficient.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230525T174622Z
